sonar.projectKey=xrdebug_laravel
sonar.organization=chevere
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.php.tests.reportPath=coverage/logs/junit.xml
sonar.php.coverage.reportPaths=coverage/logs/clover.xml
